import { BsFillMoonStarsFill } from "react-icons/bs";
import Link from "next/link"
import { useState } from "react";
import Head from "next/head";


export const Navbar = () => {
    return (
        <div>
        <Head>
          <title>Alexander Turco Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" px-10 bg-white md:px-20 lg:px-40">
            <nav className="py-5 mb-15 flex justify-between dark:text-white">
              <Link href="/">
                <a className="font-burtons text-xl text-black">alexanderturco</a>
              </Link>
              <ul className="flex items-center">
                <li>
                  <Link href="/">
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 "
                  >
                    Home
                  </a>
                  </Link>
                </li>
                <li>
                  <Link href="/about">
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  >
                    About
                  </a>
                  </Link>
                </li>
                <li>
                  <Link href="/contact">
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  >
                    Contact
                  </a>
                  </Link>
                </li>
              </ul>
            </nav>
            </main>
            </div>
    )
} 