import { BsFillMoonStarsFill } from "react-icons/bs";
import Link from "next/link"
import { useState } from "react";
import Head from "next/head";

export const Navbar = () => {
    return (
        <div className="px-10">
          <main className="flex md:px-20 lg:px-40">
        <Head>
          <title>Alexander Turco Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href= "/book.ico"/>
        </Head>
            <nav className="flex px-10 md:px-20 lg:px-40 py-5 mb-15 mx-auto">
              <Link href="/">
                <a className=" font-burtons text-xl text-black">alexanderturco</a>
              </Link>
              <ul className="flex">
                <li>
                  <Link href="/">
                  <a
                    className=" bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 "
                  >
                    Home
                  </a>
                  </Link>
                </li>
                <li>
                  <Link href="/projects">
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  >
                    Projects
                  </a>
                  </Link>
                </li>
                <li>
                  <Link href="/contact">
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  >
                    Contact
                  </a>
                  </Link>
                </li>
              </ul>
            </nav>
            </main>
            </div>
    )
} 